apiVersion : apps/v1
kind: Deployment
metadata:
  name: "sami-ef03"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "sami-ef03"
  template:
    metadata:
      labels:
        app: "sami-ef03"
    spec:
      containers:
        - name: "sami-ef03"
          image: "sami71.azurecr.io/sami"
          ports:
          - containerPort: 80