apiVersion: v1
kind: Service
metadata:
    name: "sami-ef03"
    labels:
        app: "sami-ef03"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "sami-ef03"