on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n Sami71 -g Sami71a689-rg --location "East US" --sku Standard --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n Sami71 --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n Sami71 --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n Sami71 --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: sami71.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t sami71.azurecr.io/sami:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push sami71.azurecr.io/sami:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_sami_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep sami9164 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace sami9164`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: sami9164
        container-registry-url: sami71.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: samidockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: sami9164
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          sami71.azurecr.io/sami:${{ github.sha }}
        imagepullsecrets: |
          samidockerauth   
